apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: custom-targets-pipeline
serialPipeline:
  stages:
  - targetId: sample-env
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: sample-env
customTarget:
  customTargetType: basic-custom-target
---

apiVersion: deploy.cloud.google.com/v1
kind: CustomTargetType
metadata:
  name: basic-custom-target
customActions:
  renderAction: custom-render
  deployAction: custom-deploy
  includeSkaffoldModules:
  - configs:
    googleCloudBuildRepo:
      repository: projects/katiexzhang-testing/locations/us-central1/connections/git/repositories/custom-target-quickstart
      path: skaffold.yaml
      ref: bf5edef
